module.exports = {
  singleQuote: true,
  bracketSpacing: true,
  jsxBracketSameLine: true,
  endOfLine: 'auto',
  arrowParens: 'avoid',
  bracketSameLine: true,
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: false,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: true,
  vueIndentScriptAndStyle: false,
}
